DotNet Bookstore/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DotNet_Bookstore.Data;
using DotNet_Bookstore.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace DotNet_Bookstore.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BooksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Books.Include(b => b.Category).OrderBy(b => b.Author).ThenBy(b => b.Title);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Books/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories.OrderBy(c => c.Name), "CategoryId", "Name");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookId,Author,Title,Price,MatureContent,CategoryId")] Book book, IFormFile? image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    // attach new unique file name to the new book object
                    book.Image = UploadImage(image);
                }
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", book.CategoryId);
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories.OrderBy(c => c.Name), "CategoryId", "Name", book.CategoryId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookId,Author,Title,Price,MatureContent,CategoryId")] Book book, IFormFile? image, string? CurrentImage)
        {
            if (id != book.BookId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // upload image if there is one
                    if (image != null)
                    {
                        book.Image = UploadImage(image);
                    }
                    else
                    {
                        // keep the current image if no new image is uploaded
                        // if this book already has an image
                        if (CurrentImage != null)
                        {
                            book.Image = CurrentImage;
                        }
                    }
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", book.CategoryId);
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books.FindAsync(id);
            if (book != null)
            {
                _context.Books.Remove(book);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.BookId == id);
        }

        private static string UploadImage(IFormFile image)
        {
            // get temp location of uploaded file
            var filePath = Path.GetTempFileName();
            // use globally unique identifier (GUID) to create a unique file name
            // e.g., 12345678-1234-1234-1234-123456789012-book1.jpg
            var fileName = Guid.NewGuid().ToString() + "-" + image.FileName;
            // set destination path dynamically so it runs on any system
            var uploadPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/books", fileName);
            using (var stream = new FileStream(uploadPath, FileMode.Create))
            {
                image.CopyTo(stream);
            }
            // return new file name
            return fileName;
        }
    }
}

DotNet Bookstore/Controllers/ShopController.cs
using DotNet_Bookstore.Data;
using Microsoft.AspNetCore.Mvc;
using DotNet_Bookstore.Models;
using Microsoft.EntityFrameworkCore;


namespace DotNet_Bookstore.Controllers
{
    public class ShopController : Controller
    {
        // Class level DBContext connenction object
        private readonly ApplicationDbContext _context;

        // Constructor that accepts the DBContext object
        public ShopController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var categories = _context.Categories.OrderBy(c => c.Name).ToList();
            return View(categories);
        }

        //  Get: /Shop/ShopByCategory/5
        public IActionResult ShopByCategory(int id)
        {
            // Display the category name on the page based on the ID - store category name in the ViewData object
            var category = _context.Categories.Find(id);

            // return to /shop/index if category not found
            if (category == null)
            {
                return RedirectToAction("Index");
            }
            ViewData["Category"] = category.Name;

            // query the books filtered by the selected CategoryID parameter
            var books = _context.Books.Where(b => b.CategoryId == id)
                .OrderBy(b => b.Title)
                .ToList();

            // send the books to the view for display   
            return View(books); 
        }

        // POST: /Shop/AddToCart
        [HttpPost]
        public IActionResult AddToCart(int BookId, int Quantity)
        {
            // get book - to access the current book price
            var book = _context.Books.Find(BookId);

            // check if this cart already has this book 
            var cartItem = _context.CartItems.SingleOrDefault(c => c.BookId == BookId &&
                c.CustomerId == GetCustomerId());

            if (cartItem == null)
            {
                // create a new CartItem
                cartItem = new CartItem
                {
                    BookId = BookId,
                    Quantity = Quantity,
                    Price = book.Price,
                    CustomerId = GetCustomerId()
                };

                _context.Add(cartItem);
            }
            // user already has this book in cart - update the quantity
            else
            {
                cartItem.Quantity += Quantity;
                _context.Update(cartItem);
            }

            _context.SaveChanges();

            // display the cart page
            return RedirectToAction("Cart");
        }

        // identify customer for each shopping cart
        private string GetCustomerId()
        {
            // is CustomerId session var already set?
            if (HttpContext.Session.GetString("CustomerId") == null)
            {
                // if user is logged in, use their email as session var
                if (User.Identity.IsAuthenticated)
                {
                    // use user's email address as CustomerId
                    HttpContext.Session.SetString("CustomerId", User.Identity.Name);
                }
                else
                {
                    // create new session var using a GUID
                    HttpContext.Session.SetString("CustomerId", Guid.NewGuid().ToString());

                }
            }

            // return the session var so we can identify this user's cart
            return HttpContext.Session.GetString("CustomerId");
        }

        // GET: /Shop/Cart
        public IActionResult Cart()
        {
            // get current customer to filter CartItems query to fetch & display
            var customerId = GetCustomerId();

            // get current cart items and parent Book objects for current customer - JOIN to parent Book to get Book details
            var cartItems = _context.CartItems
                .Include(c => c.Book).OrderBy(c => c.Book.Title)
                .Where(c => c.CustomerId == customerId).ToList();

            // count total of items in cart - for navbar display & store in Session var
            var itemCount = (from c in cartItems
                             select c.Quantity).Sum();
            HttpContext.Session.SetInt32("ItemCount", itemCount);

            return View(cartItems);
        }

        // GET: /Shop/RemoveFromCart/6
        public IActionResult RemoveFromCart(int id)
        {
            // find the item for deletion
            var cartItem = _context.CartItems.Find(id);

            // delete
            _context.CartItems.Remove(cartItem);
            _context.SaveChanges();

            // refresh and display cart
            return RedirectToAction("Cart");
        }

    }
}

DotNet Bookstore/Views/Shop/Cart.cshtml
@model IEnumerable<DotNet_Bookstore.Models.CartItem>

@{
    ViewData["Title"] = "Cart";
}

<h1>Cart</h1>

@* <p>
    <a asp-action="Create">Create New</a>
</p> *@
@if (Model.Count() == 0)
{
    <h4>Your cart is empty.</h4>
    <a asp-action="Index" class="btn btn-primary">Start Shopping</a>
}
else
{
    decimal total = 0;
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Book)
                </th>
                <th></th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                @*             <th>
                @Html.DisplayNameFor(model => model.CustomerId)
            </th> *@
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                total += (item.Price * item.Quantity);
                <tr>
                    <td>
                        <a asp-controller="Books" asp-action="Details" asp-route-id="@item.BookId">
                            @Html.DisplayFor(modelItem => item.Book.Title)
                        </a>
                    </td>
                    <td>
                        @if (item.Book.Image != null)
                        {
                            <img src="~/img/books/@item.Book.Image" alt="Book Cover" class="img-fluid img-thumbnail cart-images" />
                        }
                        else
                        {
                            <img src="~/img/books/bookcover-placeholder.jpg" alt="Book Cover" class="img-fluid img-thumbnail cart-images" />
                        }
                    </td>
                    <td>
                        @String.Format("{0:C}", item.Price)
                    </td>
                    @*             <td>
                @Html.DisplayFor(modelItem => item.CustomerId)
            </td> *@
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @*                 <a asp-action="Edit" asp-route-id="@item.CartItemId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CartItemId">Details</a> *@ 
                        <a asp-action="RemoveFromCart" asp-route-id="@item.CartItemId" onclick="return confirmDelete();">Remove</a>
                    </td>
                </tr>
            }
            @* display total *@
            <tr>
                <td colspan="2">
                <td><strong><span class="text-primary">Total: </span>@String.Format("{0:c}", total)</strong>	 </td>
                <td>
                    <a class="btn btn-primary" asp-action="Index">
                        Continue Shopping
                    </a>
                </td>
                <td>
                    <a class="btn btn-primary" asp-action="Checkout">
                        Checkout
                    </a>
                </td>
            </tr>
        </tbody>
    </table>

}

DotNet Bookstore/Views/Shop/Index.cshtml
@model IEnumerable<DotNet_Bookstore.Models.Category>

@{
    ViewData["Title"] = "Shop Our Store";
}

<h1>Shop Our Store</h1>
<section class="row card-group">
    @foreach (var c in Model)
    {
        <div class="col-sm-6 col-lg-4 mb-3">
            <div class="card mb-4 text-center h-100">
                <div class="card-body">
                    <a asp-controller="Shop" asp-action="ShopByCategory" asp-route-id="@c.CategoryId">@c.Name</a>
                </div>
            </div>
        </div>
    }
</section>

DotNet Bookstore/Views/Shop/ShopByCategory.cshtml
@model IEnumerable<DotNet_Bookstore.Models.Book>

@{
    ViewData["Title"] = "Shop By Category";
}

<h1 class="text-center bg-light text-dark">You are shopping for: @ViewData["Category"]</h1>


<section class="row card-group">

    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-lg-4 mb-3">
            <div class="card mb-4 text-center h-100">
                <div class="card-body">
                    <a asp-controller="Books" asp-action="Details" asp-route-id="@item.BookId" class="h5">
                        @item.Title
                    </a>
                    <h6>@item.Author</h6>
                    <h6>@String.Format("{0:c}", item.Price)</h6>
                    @if (@item.Image != null)
                    {
                        <img src="~/img/books/@item.Image" alt="Book Cover" class="img-fluid img-thumbnail" style="max-width:70%" />
                    }
                    else
                    {
                        <img src="~/img/books/bookcover-placeholder.jpg" alt="Book Cover" class="img-fluid img-thumbnail" style="max-width:70%" />
                    }

                    <form method="post" action="/Shop/AddToCart">
                        <input type="hidden" name="BookId" value="@item.BookId" />
                        <fieldset class="form-group mt-3">
                            <label for="Quantity">Quantity: </label>
                            <input type="number" id="Quantity" name="Quantity" required min="1" max="9999" value="1" class="input-small" />
                        </fieldset>
                        <button class="btn btn-primary m-2">
                            Add to Cart
                        </button>
                    </form>

                </div>
            </div>
        </div>
    }

</section>